#
# Define the min and max amount of items to spawn in a chest.
#
chest-min-items: 2
chest-max-items: 4

#
# Define the tier list with the following scheme
# '<tier name>'
#   1:
#     material: <material name> - can be found in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#     chance: <chance of item spawn> - the higher, the more likely it will spawn in a chest
#     minAmount: <min amount>
#     maxAmount: <max amount>
#     enchantments:
#        1:
#          enchantment: <name of the enchantment>
#          enchantmentLevel: <level of the enchantment>
#        2:
#          enchantment: <name of the enchantment>
#          enchantmentLevel: <level of the enchantment>
#
#     potionType: <potion type> - can be found in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html (only for potions)
#     potionExtended: <true / false> - if set to true, the potion effect lasts the extended time (only for potions)
#     potionUpgraded: <true / false> - if set to true, the potion is level 2, otherwise it is level 1 (only for potions)
#
tier-list:
  'COMMON':
    1:
      material: WOODEN_AXE
      chance: 100
    2:
      material: APPLE
      chance: 100
    3:
      material: BOW
      chance: 50
    4:
      material: ARROW
      minAmount: 2
      maxAmount: 6
      chance: 80
    5:
      material: DIAMOND
      minAmount: 1
      maxAmount: 2
      chance: 5
    6:
      material: GOLDEN_CHESTPLATE
      chance: 30
    7:
      material: LEATHER_LEGGINGS
      enchantments:
        1:
          enchantment: PROJECTILE_PROTECTION
          enchantmentLevel: 1
      chance: 60
    8:
      material: COOKIE
      minAmount: 4
      maxAmount: 8
      chance: 80
  'RARE':
    1:
      material: STONE_SWORD
      chance: 100
    2:
      material: IRON_SWORD
      chance: 10
    3:
      material: IRON_CHESTPLATE
      chance: 30
    4:
      material: CHAINMAIL_HELMET
      chance: 50
    5:
      material: GOLDEN_APPLE
      minAmount: 1
      maxAmount: 3
      chance: 15
    6:
      material: CHAINMAIL_BOOTS
      chance: 100
    7:
      material: CHAINMAIL_LEGGINGS
      chance: 50
    8:
      material: LEATHER_LEGGINGS
      chance: 60
    9:
      material: DIAMOND_HELMET
      chance: 30
    10:
      material: WOODEN_SWORD
      enchantments:
        1:
          enchantment: FIRE_ASPECT
          enchantmentLevel: 2
        2:
          enchantment: MENDING
          enchantmentLevel: 1
      chance: 15
  'MEDIC':
    1:
      material: POTION
      potionType: FIRE_RESISTANCE
      chance: 100
    2:
      material: POTION
      potionType: INSTANT_HEAL
      chance: 70
    3:
      material: POTION
      potionType: INSTANT_HEAL
      potionExtended: false
      potionUpgraded: true
      chance: 30
    4:
      material: POTION
      potionType: INSTANT_HEAL
      potionUpgraded: true
      chance: 15
    5:
      material: POTION
      potionType: REGEN
      chance: 30
    6:
      material: SPLASH_POTION
      potionType: INSTANT_HEAL
      chance: 20
    7:
      material: SPLASH_POTION
      potionType: INSTANT_HEAL
      potionUpgraded: true
      chance: 10
    8:
      material: CAKE
      minAmount: 1
      maxAmount: 3
      chance: 60
    9:
      material: WATER_BUCKET
      chance: 50
    10:
      material: ENDER_PEARL
      minAmount: 1
      maxAmount: 2
      chance: 15
    11:
      material: POTION
      potionType: FIRE_RESISTANCE
      potionExtended: true
      chance: 30

#
# chest spawn locations can and should be set by comment
# they will be stored with the following scheme:
# '<xyz location of the chest>':
#   world: <name of the world>
#   tier: <tier name as defined in the tier list>
#   x: <x location>
#   y: <y location>
#   z: <z location>
#   facing: <facing direction of the chest>
#
chest-spawn-locations:


messages:
  no-permission: "&cYou don't have permissions to execute this command."
  chests-spawned: "&bSpawned {amount} chests with loot."
  chest-spawn-location-added: "&bAdded new spawn location for chest with tier {tier}"
  chest-spawn-location-removed: "&bRemoved spawn location of chest."
  error-specify-tier: "&cError: Please specify a tier for this chest."